import os
from waflib.extras.layout import Product, Component

publicHeaders = [
    'config.hpp',
    'event.hpp',
    'event.hxx',
    'roster.hpp']

sourceFiles = [
    'event.cxx',
    'roster.cxx']

def name(context):
    return os.path.basename(str(context.path))

def configure(confCtx):
    confCtx.env.component = Component.fromContext(confCtx, name(confCtx), confCtx.env.product)
    confCtx.env.product.addComponent(confCtx.env.component)

def build(buildCtx):
    buildCtx.env.component = buildCtx.env.product.getComponent(name(buildCtx))
    publishTaskList=[]
    for header in publicHeaders:
	publishTask='publish_%s' % header
	buildCtx(
		name=publishTask,
		rule='cp ${SRC} ${TGT}',
		source=header,
		target=os.path.join(buildCtx.env.component.build_tree.includePathFromBuild(buildCtx), header),
		install_path=os.path.join(buildCtx.env.component.install_tree.include, os.path.dirname(header)))
	publishTaskList.append(publishTask)
    buildCtx.stlib(
	    name='stlib_robocup2Dsim_server',
	    source=[buildCtx.path.find_node(source) for source in sourceFiles],
	    target=os.path.join(buildCtx.env.component.build_tree.libPathFromBuild(buildCtx), 'robocup2Dsim_server'),
	    includes=buildCtx.env.component.include_path_list,
	    defines=['SHLIB_BUILD'],
	    cxxflags=buildCtx.env.CXXFLAGS,
	    linkflags=buildCtx.env.LDFLAGS,
	    libpath=buildCtx.env.component.lib_path_list,
	    rpath=buildCtx.env.component.rpath_list,
	    use=['TURBO_STLIB',
		    'ASIO_STLIB',
		    'CAPNPROTO_STLIB',
		    'ENET_STLIB',
		    'BEAM_STLIB',
		    'GLOG_STLIB',
		    'stlib_robocup2Dsim_runtime',
		    'SNAPBOX2D_STLIB',
		    'stlib_robocup2Dsim_engine',
		    'stlib_robocup2Dsim_common',
		    'stlib_robocup2Dsim_srprotocol',
		    'stlib_robocup2Dsim_csprotocol'],
	    install_path=buildCtx.env.component.install_tree.lib,
	    after=publishTaskList)
    buildCtx.program(
	    name='exe_robocup2Dsim_server',
	    source=[buildCtx.path.find_node('main.cxx'),
		    buildCtx.path.find_node('client_io.cxx'),
		    buildCtx.path.find_node('ref_io.cxx')],
	    target=os.path.join(buildCtx.env.component.build_tree.binPathFromBuild(buildCtx), 'robocup2Dsim_server'),
	    defines=['ASIO_STANDALONE', 'ASIO_SEPARATE_COMPILATION'],
	    includes=[buildCtx.path.get_src().abspath()] + buildCtx.env.component.include_path_list,
	    cxxflags=buildCtx.env.CXXFLAGS,
	    linkflags=buildCtx.env.LDFLAGS,
	    use=['TURBO_STLIB',
		    'ASIO_STLIB',
		    'CAPNPROTO_STLIB',
		    'ENET_STLIB',
		    'BEAM_STLIB',
		    'GLOG_STLIB',
		    'stlib_robocup2Dsim_runtime',
		    'SNAPBOX2D_STLIB',
		    'stlib_robocup2Dsim_engine',
		    'stlib_robocup2Dsim_common',
		    'stlib_robocup2Dsim_srprotocol',
		    'stlib_robocup2Dsim_csprotocol',
		    'stlib_robocup2Dsim_server'],
	    libpath=[buildCtx.path.get_bld().abspath()] + buildCtx.env.component.lib_path_list,
	    rpath=buildCtx.env.component.rpath_list,
	    install_path=buildCtx.env.component.install_tree.bin,
	    after=['stlib_robocup2Dsim_runtime',
		    'stlib_robocup2Dsim_engine',
		    'stlib_robocup2Dsim_common',
		    'stlib_robocup2Dsim_srprotocol',
		    'stlib_robocup2Dsim_csprotocol',
		    'stlib_robocup2Dsim_server'])
