from waflib.extras.layout import Solution, Product

NAME = 'robocup2Dsim'

def options(optCtx):
    optCtx.add_option('--test', action='store', default='', dest='test')

def configure(confCtx):
    confCtx.env.product = Product.fromContext(confCtx, NAME, confCtx.env.solution)
    confCtx.recurse('runtime')
    confCtx.recurse('engine')
    confCtx.recurse('server')

def build(buildCtx):
    buildCtx.env.product = buildCtx.env.solution.getProduct(NAME)
    buildCtx.recurse('runtime')
    buildCtx.recurse('engine')
    buildCtx.recurse('server')
