import os
import waflib.extras.capnproto
from waflib.extras.layout import Product, Component

def name(context):
    return os.path.basename(str(context.path))

publicHeaders = [
    'ecs_db.hpp',
    'ecs_db.hxx',
    'dynamics.hpp',
    'primitives.hpp',
    'primitives.hxx',
    'physics.hpp',
    'ram_db.hpp',
    'ram_db.hxx']

def configure(confCtx):
    confCtx.env.component = Component.fromContext(confCtx, name(confCtx), confCtx.env.product)
    confCtx.env.product.addComponent(confCtx.env.component)

def build(buildCtx):
    buildCtx.env.component = buildCtx.env.product.getComponent(name(buildCtx))
    headerPublishTaskList=[]
    for header in publicHeaders:
	publishTask='publish_%s' % header
	buildCtx(
		name=publishTask,
		rule='cp ${SRC} ${TGT}',
		source=header,
		target=os.path.join(buildCtx.env.component.build_tree.includePathFromBuild(buildCtx), header),
		install_path=os.path.join(buildCtx.env.component.install_tree.include, os.path.dirname(header)))
	headerPublishTaskList.append(publishTask)
    buildCtx.stlib(
	    name='stlib_robocup2Dsim_engine',
	    source=[buildCtx.path.find_node('ecs_db.cxx'),
		    buildCtx.path.find_node('physics.cxx')] +
		    [buildCtx.root.find_node(lib) for lib in buildCtx.env['SNAPBOX2D_STLIB_PATH']],
	    target=os.path.join(buildCtx.env.component.build_tree.libPathFromBuild(buildCtx), 'robocup2Dsim_engine'),
	    includes=['.'] + buildCtx.env.component.include_path_list,
	    libpath=buildCtx.env.component.lib_path_list,
	    cxxflags=buildCtx.env.CXXFLAGS,
	    linkflags=buildCtx.env.LDFLAGS,
	    use=['SNAPBOX2D_STLIB'],
	    install_path=buildCtx.env.component.install_tree.lib,
	    after=headerPublishTaskList)
