import os
from waflib.extras.layout import Product, Component

def name(context):
    return os.path.basename(str(context.path))

def configure(confCtx):
    confCtx.env.component = Component.fromContext(confCtx, name(confCtx), confCtx.env.product)
    confCtx.env.product.addComponent(confCtx.env.component)

def build(buildCtx):
    buildCtx.env.component = buildCtx.env.product.getComponent(name(buildCtx))
    buildCtx.program(
	    name='exe_ram_db_test',
	    source=[buildCtx.path.find_node('ram_db_test.cxx')] +
		    [buildCtx.root.find_node(lib) for lib in buildCtx.env['TURBO_STLIB_PATH']] +
		    [buildCtx.root.find_node(lib) for lib in buildCtx.env['SNAPBOX2D_STLIB_PATH']],
	    target=os.path.join(buildCtx.env.component.build_tree.testPathFromBuild(buildCtx), 'ram_db_test'),
	    defines=['GTEST_HAS_PTHREAD=1'],
	    includes=['.'] + buildCtx.env.component.include_path_list,
	    cxxflags=buildCtx.env.CXXFLAGS,
	    linkflags=buildCtx.env.LDFLAGS,
	    use=['GTEST', 'SNAPBOX2D_STLIB', 'TURBO_STLIB', 'stlib_robocup2Dsim_engine'],
	    libpath=['.'] + buildCtx.env.component.lib_path_list,
	    rpath=buildCtx.env.component.rpath_list,
	    install_path=None)
