import os
import waflib.extras.capnproto
from waflib.extras.layout import Product, Component

def name(context):
    return os.path.basename(str(context.path))

commonCapnpFiles=[
	'command.capnp',
	'control.capnp',
	'entity.capnp',
	'error.capnp',
	'field.capnp',
	'judgement.capnp',
	'metadata.capnp',
	'physics.capnp',
	'rule.capnp']

publicHeaders = [
    'entity.hpp']

def configure(confCtx):
    confCtx.env.component = Component.fromContext(confCtx, name(confCtx), confCtx.env.product)
    confCtx.env.product.addComponent(confCtx.env.component)

def build(buildCtx):
    buildCtx.env.component = buildCtx.env.product.getComponent(name(buildCtx))
    commonCxxNodeList=[]
    commonHNodeList=[]
    commonCapnpTaskList=[]
    commonPublishTaskList=[]
    for capnpFile in commonCapnpFiles:
	compileTask='capnp_%s' % capnpFile
	capnpNode=buildCtx.path.find_node(capnpFile)
	cxxNode=capnpNode.change_ext('.capnp.c++').get_bld()
	hNode=capnpNode.change_ext('.capnp.h').get_bld()
	waflib.extras.capnproto.define_task_gen(buildCtx,
		name=compileTask,
		source=[capnpNode],
		target=[cxxNode, hNode],
		includes=[buildCtx.path.get_src().abspath(), buildCtx.srcnode.find_node('src').abspath()])
	publishTask='publish_%s.h' % capnpFile
	buildCtx(
		name=publishTask,
		rule='cp ${SRC} ${TGT}',
		source=hNode,
		target=os.path.join(buildCtx.env.component.build_tree.includePathFromBuild(buildCtx), os.path.basename(str(hNode))),
		after=compileTask)
	commonCxxNodeList.append(cxxNode)
	commonHNodeList.append(hNode)
	commonCapnpTaskList.append(compileTask)
	commonPublishTaskList.append(publishTask)
    headerPublishTaskList=[]
    for header in publicHeaders:
	publishTask='publish_%s' % header
	buildCtx(
		name=publishTask,
		rule='cp ${SRC} ${TGT}',
		source=header,
		target=os.path.join(buildCtx.env.component.build_tree.includePathFromBuild(buildCtx), header),
		after=commonPublishTaskList,
		install_path=os.path.join(buildCtx.env.component.install_tree.include, os.path.dirname(header)))
	headerPublishTaskList.append(publishTask)
    buildCtx.stlib(
	    name='stlib_robocup2Dsim_common',
	    source=commonCxxNodeList,
	    target=os.path.join(buildCtx.env.component.build_tree.libPathFromBuild(buildCtx), 'robocup2Dsim_common'),
	    includes=['.'] + buildCtx.env.component.include_path_list,
	    libpath=buildCtx.env.component.lib_path_list,
	    cxxflags=buildCtx.env.CXXFLAGS,
	    linkflags=buildCtx.env.LDFLAGS,
	    install_path=buildCtx.env.component.install_tree.lib,
	    after=headerPublishTaskList +
		    commonCapnpTaskList)
