import os
from waflib.extras.layout import Product, Component

def name(context):
    return os.path.basename(str(context.path))

def configure(confCtx):
    confCtx.env.component = Component.fromContext(confCtx, name(confCtx), confCtx.env.product)
    confCtx.env.product.addComponent(confCtx.env.component)

def build(buildCtx):
    buildCtx.env.component = buildCtx.env.product.getComponent(name(buildCtx))
    buildCtx.program(
	    name='exe_robocup2Dsim_client',
	    source=[buildCtx.path.find_node('main.cxx'),
		    buildCtx.path.find_node('engine.cxx'),
		    buildCtx.path.find_node('server_io.cxx'),
		    buildCtx.path.find_node('bot_io.cxx')],
	    target=os.path.join(buildCtx.env.component.build_tree.binPathFromBuild(buildCtx), 'robocup2Dsim_client'),
	    defines=['ASIO_STANDALONE', 'ASIO_SEPARATE_COMPILATION'],
	    includes=[buildCtx.path.get_src().abspath()] + buildCtx.env.component.include_path_list,
	    cxxflags=buildCtx.env.CXXFLAGS,
	    linkflags=buildCtx.env.LDFLAGS,
	    use=['TURBO_STLIB',
		    'ASIO_STLIB',
		    'CAPNPROTO_STLIB',
		    'ENET_STLIB',
		    'BEAM_STLIB',
		    'GLOG_STLIB',
		    'stlib_robocup2Dsim_runtime',
		    'SNAPBOX2D_STLIB',
		    'stlib_robocup2Dsim_engine',
		    'stlib_robocup2Dsim_common',
		    'stlib_robocup2Dsim_bcprotocol',
		    'stlib_robocup2Dsim_csprotocol'],
	    libpath=[buildCtx.path.get_bld().abspath()] + buildCtx.env.component.lib_path_list,
	    rpath=buildCtx.env.component.rpath_list,
	    install_path=buildCtx.env.component.install_tree.bin,
	    after=['stlib_robocup2Dsim_runtime',
		    'stlib_robocup2Dsim_engine',
		    'stlib_robocup2Dsim_common',
		    'stlib_robocup2Dsim_bcprotocol',
		    'stlib_robocup2Dsim_csprotocol'])
